# Generated by Django 4.2.1 on 2023-06-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='feedback',
            new_name='order',
        ),
    ]
